name: Sync to Gitee

on:
  push

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: Yikun/hub-mirror-action@v1.4
        with:
          src: 'github/WangHaonie'
          dst: 'gitee/WangHaonie'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          static_list: 'CEETimerCSharpWinForms'
          debug: true
          cache_path: /github/workspace/hub-mirror-cache